# Generated by Django 5.0.6 on 2024-06-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0002_alter_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='noted',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Closed', 'closed')], default='Pending', max_length=155),
        ),
    ]
