# Generated by Django 5.0.6 on 2024-06-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0002_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='content',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
