# Generated by Django 5.0.6 on 2024-06-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0002_rename_timestamp_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=1021),
        ),
    ]
