# Generated by Django 5.0.6 on 2024-06-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_userregister_groups_userregister_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
