# Generated by Django 5.0.6 on 2024-06-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0010_remove_userregister_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userregister',
            name='roles',
            field=models.ManyToManyField(related_name='users', to='Login.role'),
        ),
    ]
