# Generated by Django 5.0.6 on 2024-06-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0011_role_userregister_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
